services:
  # --- PRODUCCIÓN ---
  - type: web
    name: streetweb-prod
    runtime: python
    rootDir: Arquitectura
    buildCommand: bash build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 90 run:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: APP_ENV
        value: production

  # --- DESARROLLO ---
  - type: web
    name: streetweb-dev
    runtime: python
    rootDir: Arquitectura
    buildCommand: bash build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 90 run:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: APP_ENV
        value: development
